### PR TITLE
add OA worlddem notebook

### PR DESCRIPTION
**Pull request by marooned20**
Adds data access notebook example for OA worlddem block.

Items:
* [ ] Ran test & live-tests
* [ ] Implemented (new) unit tests
* [x] Removed credentials
* [x] Removed argument pointing to staging
* [ ] Updated [documentation](sdk.up42.com)

For release:
* [ ] Bumped version
* [ ] Added changelog
* [ ] Updated announcement banner

### CODE REVIEW

**Comment by chrieke** [comment]
Can it be visualized with `job.plot_results()`?

**Review by thaisbendixen — APPROVED** [review]
LGTM!

**Review by nb-42 — COMMENTED** [review]
LGTM. The project ID is twice in the code, once with '1234' and once with '76f9c...'.

**Comment by marooned20** [comment]
> Can it be visualized with `job.plot_results()`? Otherwise LGTM.

Good point, I thought I added it. Coming up

**Comment by marooned20** [comment]
> LGTM. The project ID is twice in the code, once with '1234' and once with '76f9c...'.

@nb-42 the `1234` is the actual project credentials, hence masked and the other one is just an identifier for the project. We safe here! :)

**Pull request merged**
