### PR TITLE
Add CircleCI and GitHub action up4621

### PR DESCRIPTION
**Pull request by rodrigoalmeida94**
Add Circle CI config to enable live testing and deployment in CI. Fix a couple of issues in tests. 

In addition add Github Actions to deploy docs in master.

**What changes from now on:**
- Any deployment of a new package version should be done via CircleCI with the new approve to deploy in master
- Live tests will be run every night at 12AM.
- Any merge into master that changes the documentation will trigger a deployment of the docs

Items:
* [x] Ran test & live-tests
* [x] Implemented (new) unit tests
* [na] Removed credentials
* [na] Removed argument pointing to staging
* [na] Updated [documentation](sdk.up42.com)

### CODE REVIEW

**Review by nekhtiari — APPROVED** [review]
Nice

**Review by chrieke — COMMENTED** [review]
LGTM, nice! Please hold till livetests are fixed & we added a simple e2e test.

**Comment by chrieke** [comment]
@rodrigoalmeida94 Used it similar to [rio-tiler](https://github.com/cogeotiff/rio-tiler/blob/master/.github/workflows/deploy_mkdocs.yml) now without the dedicated mkdocs action, that way at least the installation is simple. Fixed the systemlink issues (You were right in the morning, only worked for me because I still had an undetected syslink file).

Locally in `act` it builds successfully now, but stops at the last step of copying the files to gh, saying it can not establish the authenticity of gh. Looking at rio-tiler it might just work when used for real. 

How did you test the action on the branch before merging?

**Comment by rodrigoalmeida94** [comment]
> @rodrigoalmeida94 Used it similar to [rio-tiler](https://github.com/cogeotiff/rio-tiler/blob/master/.github/workflows/deploy_mkdocs.yml) now without the dedicated mkdocs action, that way at least the installation is simple. Fixed the systemlink issues (You were right in the morning, only worked for me because I still had an undetected syslink file).
> 
> Locally in `act` it builds successfully now, but stops at the last step of copying the files to gh, saying it can not establish the authenticity of gh. Looking at rio-tiler it might just work when used for real.
> 
> How did you test the action on the branch before merging?

Replaced it now with mv to make things simple! But deployment was success-full :)

**Review by chrieke — APPROVED** [review]
LGTM!! 🚀🚀🚀🚀🚀🚀🚀🚀🚀

**Review by markusuwe — APPROVED** [review]
Great!

**Pull request merged**
