### PR TITLE
Update visual blocks ids and name

### PR DESCRIPTION
**Pull request by thaisbendixen**
This PR addresses and solves the following bug ticket https://up42.atlassian.net/browse/UP-5473?atlOrigin=eyJpIjoiNWFhN2EyN2JjOTI1NGI5ZWEyZjdlYWQ3MWQzZTk5NDkiLCJwIjoiaiJ9

The weekly e2e and live tests were failing as they were using the ids and names of Sentinel-2 L2A (GeoTIFF) which now has been replaced by the Sentinel-2 L2A Visual (GeoTIFF).

Items:
* [x] Ran test & live-tests
* [x] Implemented (new) unit tests
* [ ] Remove commented tests
* [ ] Updated [documentation](sdk.up42.com)

For release:
* [ ] Bumped version
* [ ] Added changelog
* [ ] Updated announcement banner

### CODE REVIEW

**Review by markusuwe — APPROVED** [review]
Wow, so many places that need to be changed.

LGTM

**Review by rodrigoalmeida94 — APPROVED** [review]
Nice and thorough!

**Comment by chrieke** [comment]
Great! Thanks for taking care of all of this and even the docs as part of a bug ticket!

**Review by chrieke — APPROVED** [review]
Great! Thanks for taking care of all of this and even the example as part of a bug ticket!

**Review by Onyothi — APPROVED** [review]

**Pull request merged**
