### PR TITLE
add initialize_jobcollection

### PR DESCRIPTION
**Pull request by chrieke**
Simplifies the creation of jobcollections of existing jobs for the user.

### CODE REVIEW

**Review by marooned20 — APPROVED** [review]
LGTM!
with this a user can provide a jobID directly?

**Review by thaisbendixen — APPROVED** [review]
LGTM

**Review by rodrigoalmeida94 — APPROVED** [review]
LGTM

**Comment by chrieke** [comment]
@marooned20 A list of jobids, that are then contained in the jobcollection (our default return for multiple jobs). This function helps recreate that object without running the jobs again.

**Pull request merged**
