### PR TITLE
add nextmap viewshed data example

### PR DESCRIPTION
**Pull request by nekhtiari**
Adds NEXTMap ONE  plus Viewshed example block.

Items:
* [ ] Ran test & live-tests
* [ ] Implemented (new) unit tests
* [ ] Removed credentials
* [ ] Removed argument pointing to staging
* [ ] Updated [documentation](sdk.up42.com)

For release:
* [ ] Bumped version
* [ ] Added changelog
* [ ] Updated announcement banner

### CODE REVIEW

**Review by marooned20 — APPROVED** [review]
LGTM!

**Comment by chrieke** [comment]
LGTM, interesting viz!

**Review by markusuwe — COMMENTED** [review]
Generally fine, but I believe this needs a bit more explanation:
- why can't the DEM data not be downloaded and displayed (streaming data license)
- how can the visualisation be interpreted?

**Comment by nekhtiari** [comment]
> Generally fine, but I believe this needs a bit more explanation:
> 
> * why can't the DEM data not be downloaded and displayed (streaming data license)
> * how can the visualisation be interpreted?

Added!

**Pull request merged**
