### PR TITLE
Ship identification example

### PR DESCRIPTION
**Pull request by markusuwe**
Simple workflow for ship identification. Also want to show catalog and parallelization features. For the webinar will need to skip over some parts, 10 minutes are pretty short.
If available in time would also include price estimation.

### CODE REVIEW

**Review by marooned20 — APPROVED** [review]
LGTM! Nice and clean. Love the plots next to one another.
A minor cosmetic suggestion: The identified ships can be in green can be easier for visual message conveying!

**Comment by markusuwe** [comment]
> LGTM! Nice and clean. Love the plots next to one another.
> A minor cosmetic suggestion: The identified ships can be in green so that they be easier for visual message conveying!

Thanks for the suggestion. Had it green earlier, but it does not stand out on the turquoise waters. Tried a number of colors, orange worked best in the end.

**Comment by marooned20** [comment]
> > LGTM! Nice and clean. Love the plots next to one another.
> > A minor cosmetic suggestion: The identified ships can be in green so that they be easier for visual message conveying!
> 
> Thanks for the suggestion. Had it green earlier, but it does not stand out on the turquoise waters. Tried a number of colors, orange worked best in the end.

ahh okay!

**Review by chrieke — COMMENTED** [review]
LGTM. 

- Heading "Download selected SPOT images for aois" seems outdated since this section runs the whole pipeline.
- Need to add the example as a chapter entry in mkdcos.yml, analouge to the other examples.

**Review by thaisbendixen — APPROVED** [review]
"something fishy going on" lol

**Comment by markusuwe** [comment]
> LGTM.
> 
> * Heading "Download selected SPOT images for aois" seems outdated since this section runs the whole pipeline.
> * Need to add the example as a chapter entry in mkdcos.yml, analouge to the other examples.

Thanks. Did both.

**Pull request merged**
