### PR TITLE
Fix live tests up5189

### PR DESCRIPTION
**Pull request by rodrigoalmeida94**
Replace live tests based on Sobloo S2 blocks with workflow including S2 L2A Geotiff block from AWS. Add two "e2e" tests for assuring 30 sec example and catalog example are operational.

Example workflow is now S2 L2A Geotiff > Sharpening Filter.

Items:
* [x] Ran test & live-tests
* [x] Implemented (new) unit tests
* [na] Removed credentials
* [na] Removed argument pointing to staging
* [x] Updated [documentation](sdk.up42.com)

### CODE REVIEW

**Review by nekhtiari — APPROVED** [review]
Nice

**Review by markusuwe — APPROVED** [review]
Great!

**Review by nekhtiari — APPROVED** [review]

**Review by thaisbendixen — APPROVED** [review]
LGTM!

**Review by chrieke — CHANGES_REQUESTED** [review]
Nice!    30sec example in the readme & detailed example notebook in the docs needs to be adjusted as well. And all of them still use plotting specific to landsurfacetemp, need to change bands&cmap for RGB.

**Comment by rodrigoalmeida94** [comment]
> Nice! 30sec example in the readme & detailed example notebook in the docs needs to be adjusted as well. And all of them still use plotting specific to landsurfacetemp, need to change bands&cmap for RGB.

I had adjusted the examples and detailed examples, did I miss something? The CMAP is a good catch, will change.

**Comment by rodrigoalmeida94** [comment]
> > Nice! 30sec example in the readme & detailed example notebook in the docs needs to be adjusted as well. And all of them still use plotting specific to landsurfacetemp, need to change bands&cmap for RGB.
> 
> I had adjusted the examples and detailed examples, did I miss something? The CMAP is a good catch, will change.

@chrieke seems like I forgot to push some commits! Sorry about that. One other thing - this page seems to be broken https://sdk.up42.com/guides/detailed-example.ipynb. I've tried in locally in this branch and the same happens, any clue why that is? In the makefile there is some magic I don't understand with the paths, not sure if related:
```
unlink $(PWD)/docs/examples; ln -s $(PWD)/examples docs
unlink $(PWD)/docs/CHANGELOG.md; ln -s $(PWD)/CHANGELOG.md docs
mkdocs serve
```

**Comment by chrieke** [comment]
> @chrieke seems like I forgot to push some commits! Sorry about that. One other thing - this page seems to be broken https://sdk.up42.com/guides/detailed-example.ipynb. I've tried in locally in this branch and the same happens, any clue why that is? In the makefile there is some magic I don't understand with the paths, not sure if related:
> 
> ```
> unlink $(PWD)/docs/examples; ln -s $(PWD)/examples docs
> unlink $(PWD)/docs/CHANGELOG.md; ln -s $(PWD)/CHANGELOG.md docs
> mkdocs serve
> ```

The commands for `make serve`&`make gh-pages` are to systemlink the example notebooks & changelog into the docs directory before building the docs (systemlink is like a shortcut on Windows). mkdocs can only pick up files in docs subdirectories, this avoids file duplication of the examples folder. In the command a potential existing system link is first unlinked, then linkend again.

Not sure what happened here, can see via commit message that you used `make gh-pages` correctly (instead of `mkdocs serve` where I would expect this problem). Maybe some mixup with the systemlink that I'm not aware off, can you please manually remove `up42/docs/examples` if it already exists and check again when using `make serve`? Works for me on this branch.

Easiest solution to avoid any future problems would be to finally establish a dev branch and have the docs automatically reflect master via [github action](https://github.com/marketplace/actions/deploy-mkdocs). Think you suggested this a longer time ago already. If you agree can you create a task please?

**Review by chrieke — COMMENTED** [review]
Adjusted 30sec example in the repo readme still missing, then LGTM. 

Would be cool to consolidate the 30sec example in one spot and use it in the 4 different places from that one file, hope we can do some sdk improvements end of quarter.

**Comment by rodrigoalmeida94** [comment]
> github action

Nice! Will add this github action together with the live and e2e test ticket!

**Review by chrieke — APPROVED** [review]
LGTM, great effort!

**Pull request merged**
