### PR TITLE
DOC-630: Tasking notebook

### PR DESCRIPTION
**Pull request by dustgalactic**
Add a notebook to the docs

### CODE REVIEW

**Review by seedlit — COMMENTED** [review]
Nice!
Just one thing: Now that we have this notebook, we should remove the [previous tasking example notebook](https://github.com/up42/up42-py/blob/master/examples/2_tasking_order.ipynb). Can you remove it?

**Comment by dustgalactic** [comment]
> Nice! Just one thing: Now that we have this notebook, we should remove the [previous tasking example notebook](https://github.com/up42/up42-py/blob/master/examples/2_tasking_order.ipynb). Can you remove it?

Done

**Review by seedlit — APPROVED** [review]
LGTM!
Nice with the documentation URLs :)

**Review by andher1802 — APPROVED** [review]
LGTM

**Pull request merged**
