### PR TITLE
Iso time for catalog and workflow up5631

### PR DESCRIPTION
**Pull request by chrieke**
- Use the new time formatting options (iso, datetime) from https://github.com/up42/up42-py/pull/244 also in catalog search
- Move time formatting logic to utils module to simplify code structure

Items:
* [x] Ran test & live-tests
* [ ] Implemented (new) unit tests
* [ ] Removed credentials
* [ ] Removed argument pointing to staging
* [ ] Updated [documentation](sdk.up42.com)

For release:
* [ ] Bumped version
* [ ] Added changelog
* [ ] Updated announcement banner

### CODE REVIEW

**Review by marooned20 — APPROVED** [review]
Nice!
I would recommend to check out [Arrow: Better dates & times for Python](https://arrow.readthedocs.io/en/latest/). Although it adds another dependency. But might be worth it!

**Comment by thaisbendixen** [comment]
> Nice!
> I would recommend to check out [Arrow: Better dates & times for Python](https://arrow.readthedocs.io/en/latest/). Although it adds another dependency. But might be worth it!

this looks cool!!

**Review by thaisbendixen — APPROVED** [review]
LGTM!

**Comment by nekhtiari** [comment]
> Nice!
> I would recommend to check out [Arrow: Better dates & times for Python](https://arrow.readthedocs.io/en/latest/). Although it adds another dependency. But might be worth it!

wow, this Arrow thingi is really cool!

**Review by nekhtiari — APPROVED** [review]
Nice!

**Comment by chrieke** [comment]
Jup looks cool, will merge now for the new structure and then look into what we could replace with arrow!

**Pull request merged**
